//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 01:38:55 PM TRT 
//


package com.example.demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="usageSummary" type="{http://example.com/demo}usageSummary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usageSummary"
})
@XmlRootElement(name = "getCustomerUsageResponse")
public class GetCustomerUsageResponse {

    @XmlElement(required = true)
    protected UsageSummary usageSummary;

    /**
     * Gets the value of the usageSummary property.
     * 
     * @return
     *     possible object is
     *     {@link UsageSummary }
     *     
     */
    public UsageSummary getUsageSummary() {
        return usageSummary;
    }

    /**
     * Sets the value of the usageSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageSummary }
     *     
     */
    public void setUsageSummary(UsageSummary value) {
        this.usageSummary = value;
    }

}
