//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.24 at 01:38:55 PM TRT 
//


package com.example.demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for usageSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="usageSummary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="totalTransactionVolume" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="size" type="{http://example.com/demo}size"/&gt;
 *         &lt;element name="avgCustomerSatisfaction" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *         &lt;element name="numberOfRepresentetive" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="evaluation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "usageSummary", propOrder = {
    "totalTransactionVolume",
    "size",
    "avgCustomerSatisfaction",
    "numberOfRepresentetive",
    "evaluation"
})
public class UsageSummary {

    protected float totalTransactionVolume;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Size size;
    protected float avgCustomerSatisfaction;
    protected int numberOfRepresentetive;
    @XmlElement(required = true)
    protected String evaluation;

    /**
     * Gets the value of the totalTransactionVolume property.
     * 
     */
    public float getTotalTransactionVolume() {
        return totalTransactionVolume;
    }

    /**
     * Sets the value of the totalTransactionVolume property.
     * 
     */
    public void setTotalTransactionVolume(float value) {
        this.totalTransactionVolume = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Size }
     *     
     */
    public Size getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Size }
     *     
     */
    public void setSize(Size value) {
        this.size = value;
    }

    /**
     * Gets the value of the avgCustomerSatisfaction property.
     * 
     */
    public float getAvgCustomerSatisfaction() {
        return avgCustomerSatisfaction;
    }

    /**
     * Sets the value of the avgCustomerSatisfaction property.
     * 
     */
    public void setAvgCustomerSatisfaction(float value) {
        this.avgCustomerSatisfaction = value;
    }

    /**
     * Gets the value of the numberOfRepresentetive property.
     * 
     */
    public int getNumberOfRepresentetive() {
        return numberOfRepresentetive;
    }

    /**
     * Sets the value of the numberOfRepresentetive property.
     * 
     */
    public void setNumberOfRepresentetive(int value) {
        this.numberOfRepresentetive = value;
    }

    /**
     * Gets the value of the evaluation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * Sets the value of the evaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvaluation(String value) {
        this.evaluation = value;
    }

}
