spring:
  cloud:
    config:
      uri: http://localhost:8762
  application:
    name: zuul-server
server:
  port: 8762
  connection-timeout: 60000
  servlet:
    session:  
      timeout: 60s
      
   
zuul:
  host:
    connect-timeout-millis: 60000
    connection-request-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    demo:
      path: /demo/**
      url: http://localhost:8035/ 
   
    